name: Deploy Ajo-Savings
on:
  push:
    branches:
    - main

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: Install Node and Build
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm install
        - run: npm run build
        
        - name: Install Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
            
        - name: Install EB CLI using pip
          run: |
            python -m pip install --upgrade pip
            pip install awsebcli
            
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.MANAGED_INTERNSHIP_S3_ROLE }}
            aws-region: us-east-1
      
        - name: Init EB CLI
          run: eb init Ajo-Savings --platform Node.js --region us-east-1
        
        - name: Deploy to Elastic Beanstalk
          run: eb deploy Ajo-Savings-env
            